/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CabinSuitesRouteImport } from './routes/cabin-suites'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedConciergeRouteImport } from './routes/_authenticated/concierge'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AirlinesIndexRouteImport } from './routes/airlines.index'
import { Route as AirlinesSlugRouteImport } from './routes/airlines.$slug'
import { Route as ApiConciergeRouteImport } from './routes/api/concierge'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as FlightConfirmRouteImport } from './routes/flight.Confirm'
import { Route as FlightBookingRouteImport } from './routes/flight.booking'
import { Route as FlightConfirmationRouteImport } from './routes/flight.confirmation'
import { Route as FlightFareDetailsRouteImport } from './routes/flight.fare-details'
import { Route as FlightPaymentRouteImport } from './routes/flight.payment'
import { Route as FlightSearchRouteImport } from './routes/flight.search'
import { Route as RoutesRouteIdRouteImport } from './routes/routes.$routeId'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as ApiMetaSearchRouteImport } from './routes/api/meta/search'
import { Route as ApiPublicFareCacheRouteImport } from './routes/api/public/fare-cache'
import { Route as ApiPublicMetaSearchRouteImport } from './routes/api/public/meta/search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinSuitesRoute = CabinSuitesRouteImport.update({
  id: '/cabin-suites',
  path: '/cabin-suites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConciergeRoute = AuthenticatedConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AirlinesIndexRoute = AirlinesIndexRouteImport.update({
  id: '/airlines/',
  path: '/airlines/',
  getParentRoute: () => rootRouteImport,
} as any)
const AirlinesSlugRoute = AirlinesSlugRouteImport.update({
  id: '/airlines/$slug',
  path: '/airlines/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConciergeRoute = ApiConciergeRouteImport.update({
  id: '/api/concierge',
  path: '/api/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightConfirmRoute = FlightConfirmRouteImport.update({
  id: '/flight/Confirm',
  path: '/flight/Confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightBookingRoute = FlightBookingRouteImport.update({
  id: '/flight/booking',
  path: '/flight/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightConfirmationRoute = FlightConfirmationRouteImport.update({
  id: '/flight/confirmation',
  path: '/flight/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightFareDetailsRoute = FlightFareDetailsRouteImport.update({
  id: '/flight/fare-details',
  path: '/flight/fare-details',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightPaymentRoute = FlightPaymentRouteImport.update({
  id: '/flight/payment',
  path: '/flight/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightSearchRoute = FlightSearchRouteImport.update({
  id: '/flight/search',
  path: '/flight/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdRoute = RoutesRouteIdRouteImport.update({
  id: '/routes/$routeId',
  path: '/routes/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaSearchRoute = ApiMetaSearchRouteImport.update({
  id: '/api/meta/search',
  path: '/api/meta/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFareCacheRoute = ApiPublicFareCacheRouteImport.update({
  id: '/api/public/fare-cache',
  path: '/api/public/fare-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaSearchRoute = ApiPublicMetaSearchRouteImport.update({
  id: '/api/public/meta/search',
  path: '/api/public/meta/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cabin-suites': typeof CabinSuitesRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/deals': typeof DealsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/concierge': typeof AuthenticatedConciergeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/airlines/$slug': typeof AirlinesSlugRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/flight/Confirm': typeof FlightConfirmRoute
  '/flight/booking': typeof FlightBookingRoute
  '/flight/confirmation': typeof FlightConfirmationRoute
  '/flight/fare-details': typeof FlightFareDetailsRoute
  '/flight/payment': typeof FlightPaymentRoute
  '/flight/search': typeof FlightSearchRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/airlines/': typeof AirlinesIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/api/meta/search': typeof ApiMetaSearchRoute
  '/api/public/fare-cache': typeof ApiPublicFareCacheRoute
  '/api/public/meta/search': typeof ApiPublicMetaSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cabin-suites': typeof CabinSuitesRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/deals': typeof DealsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/concierge': typeof AuthenticatedConciergeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/airlines/$slug': typeof AirlinesSlugRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/flight/Confirm': typeof FlightConfirmRoute
  '/flight/booking': typeof FlightBookingRoute
  '/flight/confirmation': typeof FlightConfirmationRoute
  '/flight/fare-details': typeof FlightFareDetailsRoute
  '/flight/payment': typeof FlightPaymentRoute
  '/flight/search': typeof FlightSearchRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/admin': typeof AdminIndexRoute
  '/airlines': typeof AirlinesIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/api/meta/search': typeof ApiMetaSearchRoute
  '/api/public/fare-cache': typeof ApiPublicFareCacheRoute
  '/api/public/meta/search': typeof ApiPublicMetaSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cabin-suites': typeof CabinSuitesRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/deals': typeof DealsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/concierge': typeof AuthenticatedConciergeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/airlines/$slug': typeof AirlinesSlugRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/flight/Confirm': typeof FlightConfirmRoute
  '/flight/booking': typeof FlightBookingRoute
  '/flight/confirmation': typeof FlightConfirmationRoute
  '/flight/fare-details': typeof FlightFareDetailsRoute
  '/flight/payment': typeof FlightPaymentRoute
  '/flight/search': typeof FlightSearchRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/airlines/': typeof AirlinesIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/api/meta/search': typeof ApiMetaSearchRoute
  '/api/public/fare-cache': typeof ApiPublicFareCacheRoute
  '/api/public/meta/search': typeof ApiPublicMetaSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cabin-suites'
    | '/contact'
    | '/corporate'
    | '/deals'
    | '/privacy'
    | '/refund-policy'
    | '/sitemap'
    | '/terms'
    | '/agent'
    | '/concierge'
    | '/dashboard'
    | '/admin/dashboard'
    | '/airlines/$slug'
    | '/api/concierge'
    | '/destinations/$slug'
    | '/flight/Confirm'
    | '/flight/booking'
    | '/flight/confirmation'
    | '/flight/fare-details'
    | '/flight/payment'
    | '/flight/search'
    | '/routes/$routeId'
    | '/verify/$token'
    | '/admin/'
    | '/airlines/'
    | '/destinations/'
    | '/api/meta/search'
    | '/api/public/fare-cache'
    | '/api/public/meta/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cabin-suites'
    | '/contact'
    | '/corporate'
    | '/deals'
    | '/privacy'
    | '/refund-policy'
    | '/sitemap'
    | '/terms'
    | '/agent'
    | '/concierge'
    | '/dashboard'
    | '/admin/dashboard'
    | '/airlines/$slug'
    | '/api/concierge'
    | '/destinations/$slug'
    | '/flight/Confirm'
    | '/flight/booking'
    | '/flight/confirmation'
    | '/flight/fare-details'
    | '/flight/payment'
    | '/flight/search'
    | '/routes/$routeId'
    | '/verify/$token'
    | '/admin'
    | '/airlines'
    | '/destinations'
    | '/api/meta/search'
    | '/api/public/fare-cache'
    | '/api/public/meta/search'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/cabin-suites'
    | '/contact'
    | '/corporate'
    | '/deals'
    | '/privacy'
    | '/refund-policy'
    | '/sitemap'
    | '/terms'
    | '/_authenticated/agent'
    | '/_authenticated/concierge'
    | '/_authenticated/dashboard'
    | '/admin/dashboard'
    | '/airlines/$slug'
    | '/api/concierge'
    | '/destinations/$slug'
    | '/flight/Confirm'
    | '/flight/booking'
    | '/flight/confirmation'
    | '/flight/fare-details'
    | '/flight/payment'
    | '/flight/search'
    | '/routes/$routeId'
    | '/verify/$token'
    | '/admin/'
    | '/airlines/'
    | '/destinations/'
    | '/api/meta/search'
    | '/api/public/fare-cache'
    | '/api/public/meta/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CabinSuitesRoute: typeof CabinSuitesRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  DealsRoute: typeof DealsRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SitemapRoute: typeof SitemapRoute
  TermsRoute: typeof TermsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AirlinesSlugRoute: typeof AirlinesSlugRoute
  ApiConciergeRoute: typeof ApiConciergeRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  FlightConfirmRoute: typeof FlightConfirmRoute
  FlightBookingRoute: typeof FlightBookingRoute
  FlightConfirmationRoute: typeof FlightConfirmationRoute
  FlightFareDetailsRoute: typeof FlightFareDetailsRoute
  FlightPaymentRoute: typeof FlightPaymentRoute
  FlightSearchRoute: typeof FlightSearchRoute
  RoutesRouteIdRoute: typeof RoutesRouteIdRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AirlinesIndexRoute: typeof AirlinesIndexRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  ApiMetaSearchRoute: typeof ApiMetaSearchRoute
  ApiPublicFareCacheRoute: typeof ApiPublicFareCacheRoute
  ApiPublicMetaSearchRoute: typeof ApiPublicMetaSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabin-suites': {
      id: '/cabin-suites'
      path: '/cabin-suites'
      fullPath: '/cabin-suites'
      preLoaderRoute: typeof CabinSuitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concierge': {
      id: '/_authenticated/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof AuthenticatedConciergeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airlines/': {
      id: '/airlines/'
      path: '/airlines'
      fullPath: '/airlines/'
      preLoaderRoute: typeof AirlinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airlines/$slug': {
      id: '/airlines/$slug'
      path: '/airlines/$slug'
      fullPath: '/airlines/$slug'
      preLoaderRoute: typeof AirlinesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/concierge': {
      id: '/api/concierge'
      path: '/api/concierge'
      fullPath: '/api/concierge'
      preLoaderRoute: typeof ApiConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight/Confirm': {
      id: '/flight/Confirm'
      path: '/flight/Confirm'
      fullPath: '/flight/Confirm'
      preLoaderRoute: typeof FlightConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight/booking': {
      id: '/flight/booking'
      path: '/flight/booking'
      fullPath: '/flight/booking'
      preLoaderRoute: typeof FlightBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight/confirmation': {
      id: '/flight/confirmation'
      path: '/flight/confirmation'
      fullPath: '/flight/confirmation'
      preLoaderRoute: typeof FlightConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight/fare-details': {
      id: '/flight/fare-details'
      path: '/flight/fare-details'
      fullPath: '/flight/fare-details'
      preLoaderRoute: typeof FlightFareDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight/payment': {
      id: '/flight/payment'
      path: '/flight/payment'
      fullPath: '/flight/payment'
      preLoaderRoute: typeof FlightPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight/search': {
      id: '/flight/search'
      path: '/flight/search'
      fullPath: '/flight/search'
      preLoaderRoute: typeof FlightSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId': {
      id: '/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof RoutesRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/search': {
      id: '/api/meta/search'
      path: '/api/meta/search'
      fullPath: '/api/meta/search'
      preLoaderRoute: typeof ApiMetaSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fare-cache': {
      id: '/api/public/fare-cache'
      path: '/api/public/fare-cache'
      fullPath: '/api/public/fare-cache'
      preLoaderRoute: typeof ApiPublicFareCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/search': {
      id: '/api/public/meta/search'
      path: '/api/public/meta/search'
      fullPath: '/api/public/meta/search'
      preLoaderRoute: typeof ApiPublicMetaSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedConciergeRoute: typeof AuthenticatedConciergeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedConciergeRoute: AuthenticatedConciergeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CabinSuitesRoute: CabinSuitesRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  DealsRoute: DealsRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SitemapRoute: SitemapRoute,
  TermsRoute: TermsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AirlinesSlugRoute: AirlinesSlugRoute,
  ApiConciergeRoute: ApiConciergeRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  FlightConfirmRoute: FlightConfirmRoute,
  FlightBookingRoute: FlightBookingRoute,
  FlightConfirmationRoute: FlightConfirmationRoute,
  FlightFareDetailsRoute: FlightFareDetailsRoute,
  FlightPaymentRoute: FlightPaymentRoute,
  FlightSearchRoute: FlightSearchRoute,
  RoutesRouteIdRoute: RoutesRouteIdRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
  AirlinesIndexRoute: AirlinesIndexRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  ApiMetaSearchRoute: ApiMetaSearchRoute,
  ApiPublicFareCacheRoute: ApiPublicFareCacheRoute,
  ApiPublicMetaSearchRoute: ApiPublicMetaSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
